language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
<<<<<<< HEAD
    secure: ZJ8L+vU7tgSptVveg+yAJRHkIUCHvOZxPJPJ5lF7pHjl39OsJsSMaiuy77Cv/kLNsV6UPVGLmU4oXCdTrw8PNzcgkkOK4XIIq3xvb+JCxK/J5J0D6lTelUCXku5cQQB/PG3TSvgnMMXfjq1OC8Wuu1yg7tH9Txzonp675EIUUV0ch80CgVg+pHiBjDad4VgaSkIOcvfkV7OSo7oCjQ/ZM+JzLLBTiBL+xgr5fmlm7uafrC83pSkV4FpKWUsHz7Kbpxg3yISOVPMYI/b0ebRoTxHn+RfrFgmjrKvb7vqGfxLJBlEkVk0KEorYvBnbSpRe35Y8FXFZXA3pQxJ+t8JOhhLZauA4xlB+zNzg3jzFLh8pgbAw5EIbfrrll8XjxyNAROXmACiAkkCnU4QCnA9Q0gf8xQqvDle1hJ3a7mHY5NDBL11M06YJnUeeVNZaYmXtrsqg10M+//E1lNYA2H6Bfz0L/GsW6qmPjQnZn/hdhv/BukN8URT/1ZayVRwe0/rmlxRACuuiK+PBO7O1TNA9EMuy/5eJ4dht1wae2vaZU9tD5uBD/oPjJ1aMEpFYYePDDNfQXfOGiEzvlEvvaGNG4nIiMThX8sik1u5RPcjLRWzh9LdGOScQalPRMkB+NuMQwE9pvZ5brnNjY25J9yCALZb/0NiYiww2TYdnV3atDKI=
  branches:
    only: main
=======
    secure: fz4uSb+KZ8RF3vstlUbfgAW1eWbsEJWFrfZ9Ck6o1ytj643a2sR2lvoSXqjFc4pcrVcdQ4sV3WJ2OGKgIQ7T70C0FOiditiqWGXPhlQMeXaeUACy2IXE/7OoKmPFCg5EL0bGK1hTnRZS0zMUd9x2P27HdvVfFQHAh8sIai54KC6SqoJKQyCiJdPBu8n0luW5jlAdMpuybPx1GQ4qJclwe2hO+4EdyDGHtksw9j6kw/dD7Zr6BR2eMVtVcHcV81P8uTg+4LismNTy5R6m5RNmJkOoje1mGuoJEt7JpcOTsQyo6BkO8LtEtUd1FUeJnOmawgWxy/GUkbux+emcQLrIrVCiqHzmHcZKdflyWPNtwwlBx0l6ykdt/fkRIf13hgCVb/ClGFgnkv2YdlrLHU+aoTQxR7zPhVGbcfW69Qx1p6XHrfuZ4se5UPsS7Y+rgGqTRKAZANmmTjvfSrJpmaeU+tUZmanIT6Ec+UQcPelQGW2fetRVeGZXRAp4VtA5OO3ZEamVM0YaFEd0cBPPi28uMyXsdVCUKsSXQPVqjlF9JlyrqpOBbS0T3g9Ial29BFFQoUql4aiyhy7lhSyQWSMk/FfGhn1K4HmswktwluK2bdTVmoQl3MvY1Ukb8DuEDkJOT99ZS/WMZz+8c3wDYgml/7VRMhfTEFUHpifYf2dhkWw=
  on: main
>>>>>>> b3afa1191125923d9462dceb6a4c78c97cab36c3
  app: viewing-party-thj
  run: rails db:migrate
